package com.smartattendance.core.theme

import androidx.compose.ui.graphics.Color

// ---------- پالت روشن ----------
val PrimaryLight = Color(0xFF2E4BAE)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFDCE1FF)
val OnPrimaryContainerLight = Color(0xFF001159)
val SecondaryLight = Color(0xFF2A9D8F)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCFF2EC)
val OnSecondaryContainerLight = Color(0xFF00201C)
val TertiaryLight = Color(0xFFB9552B)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFFDBCC)
val OnTertiaryContainerLight = Color(0xFF380D00)
val BackgroundLight = Color(0xFFF7F8FC)
val OnBackgroundLight = Color(0xFF1A1C23)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF1A1C23)
val SurfaceVariantLight = Color(0xFFE3E2EE)
val OnSurfaceVariantLight = Color(0xFF464A56)
val OutlineLight = Color(0xFF767A87)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)

// ---------- پالت تاریک ----------
val PrimaryDark = Color(0xFFB7C3FF)
val OnPrimaryDark = Color(0xFF132B7F)
val PrimaryContainerDark = Color(0xFF0F2F9A)
val OnPrimaryContainerDark = Color(0xFFDCE1FF)
val SecondaryDark = Color(0xFF8AD5C9)
val OnSecondaryDark = Color(0xFF003731)
val SecondaryContainerDark = Color(0xFF005048)
val OnSecondaryContainerDark = Color(0xFFCFF2EC)
val TertiaryDark = Color(0xFFFFB593)
val OnTertiaryDark = Color(0xFF571F04)
val TertiaryContainerDark = Color(0xFF7A3317)
val OnTertiaryContainerDark = Color(0xFFFFDBCC)
val BackgroundDark = Color(0xFF12131A)
val OnBackgroundDark = Color(0xFFE3E2EC)
val SurfaceDark = Color(0xFF1C1E28)
val OnSurfaceDark = Color(0xFFE3E2EC)
val SurfaceVariantDark = Color(0xFF464A56)
val OnSurfaceVariantDark = Color(0xFFC7C6D6)
val OutlineDark = Color(0xFF9094A3)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)

// رنگ‌های وضعیت
val StatusPresent = Color(0xFF2E7D32)
val StatusPending = Color(0xFFF9A825)
val StatusAbsent = Color(0xFFC62828)
